// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Skylab.Web.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Faq = "Faq";
            public readonly string Contact = "Contact";
            public readonly string Download = "Download";
            public readonly string DownloadErrors = "DownloadErrors";
            public readonly string Licence = "Licence";
            public readonly string Program = "Program";
            public readonly string DownloadGuide = "DownloadGuide";
            public readonly string RegistrationGuide = "RegistrationGuide";
            public readonly string AdminGuide = "AdminGuide";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Faq = "Faq";
            public const string Contact = "Contact";
            public const string Download = "Download";
            public const string DownloadErrors = "DownloadErrors";
            public const string Licence = "Licence";
            public const string Program = "Program";
            public const string DownloadGuide = "DownloadGuide";
            public const string RegistrationGuide = "RegistrationGuide";
            public const string AdminGuide = "AdminGuide";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AdminGuide = "AdminGuide";
                public readonly string Contact = "Contact";
                public readonly string Download = "Download";
                public readonly string DownloadErrors = "DownloadErrors";
                public readonly string DownloadGuide = "DownloadGuide";
                public readonly string Faq = "Faq";
                public readonly string Index = "Index";
                public readonly string Licence = "Licence";
                public readonly string Program = "Program";
                public readonly string RegistrationGuide = "RegistrationGuide";
            }
            public readonly string AdminGuide = "~/Views/Home/AdminGuide.cshtml";
            public readonly string Contact = "~/Views/Home/Contact.cshtml";
            public readonly string Download = "~/Views/Home/Download.cshtml";
            public readonly string DownloadErrors = "~/Views/Home/DownloadErrors.cshtml";
            public readonly string DownloadGuide = "~/Views/Home/DownloadGuide.cshtml";
            public readonly string Faq = "~/Views/Home/Faq.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Licence = "~/Views/Home/Licence.cshtml";
            public readonly string Program = "~/Views/Home/Program.cshtml";
            public readonly string RegistrationGuide = "~/Views/Home/RegistrationGuide.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Skylab.Web.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FaqOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Faq()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Faq);
            FaqOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Contact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            ContactOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DownloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Download()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Download);
            DownloadOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DownloadErrorsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadErrors()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadErrors);
            DownloadErrorsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LicenceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Licence()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Licence);
            LicenceOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProgramOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Program()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Program);
            ProgramOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DownloadGuideOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadGuide()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadGuide);
            DownloadGuideOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegistrationGuideOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RegistrationGuide()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegistrationGuide);
            RegistrationGuideOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AdminGuideOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AdminGuide()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdminGuide);
            AdminGuideOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
